# Generated by Django 4.2.3 on 2023-08-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendship',
            old_name='to_user',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='friendship',
            old_name='from_user',
            new_name='sender',
        ),
    ]
